3. You have a dataset (internship_train.csv) that contains 53 anonymized features and a target column. Your task is to build model that predicts a target based on the proposed features. Please provide predictions for internship_hidden_test.csv file. Target metric is RMSE. The main goal is to provide github repository that contains:
jupyter notebook with analysis;
code for modeling (Python 3);
file with model predictions;
readme file;
requirements.txt file.

In [19]:
import pandas as pd
import numpy as np
import math
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error
from sklearn.metrics import accuracy_score

In [20]:
train_data = pd.read_csv('internship_train.csv')
test_data = pd.read_csv('internship_hidden_test.csv')

In [21]:
train_data.head()

,0,1,2,3,4,5,6,7,8,9,...,44,45,46,47,48,49,50,51,52,target
0,236,488,16,221,382,97,-4.472136,0.107472,0,132,...,13.340874,0.870542,1.962937,7.466666,11.547794,8.822916,9.046424,7.895535,11.010677,20.107472
1,386,206,357,232,1,198,7.810250,0.763713,1,143,...,12.484882,7.168680,2.885415,12.413973,10.260494,10.091351,9.270888,3.173994,13.921871,61.763713
2,429,49,481,111,111,146,8.602325,0.651162,1,430,...,14.030257,0.394970,8.160625,12.592059,8.937577,2.265191,11.255721,12.794841,12.080951,74.651162
3,414,350,481,370,208,158,8.306624,0.424645,1,340,...,2.789577,6.416708,10.549814,11.456437,6.468099,2.519049,0.258284,9.317696,5.383098,69.424645
4,318,359,20,218,317,301,8.124038,0.767304,1,212,...,1.886560,1.919999,2.268203,0.149421,4.105907,10.416291,6.816217,8.586960,4.512419,66.767304

In [22]:
test_data.head()

,0,1,2,3,4,5,6,7,8,9,...,43,44,45,46,47,48,49,50,51,52
0,259,388,402,340,156,382,3.316625,0.218760,1,164,...,7.163474,10.227235,0.889111,9.190222,4.670908,0.931525,7.634177,0.158196,13.432551,2.511191
1,441,192,381,421,452,123,-8.888194,0.700228,0,349,...,10.619064,9.339161,4.221861,0.595563,13.865748,0.328453,11.507599,9.107966,1.302407,11.105604
2,83,129,107,156,247,191,2.645751,0.494556,1,297,...,1.819890,10.670237,10.350867,5.134417,5.898995,8.374986,4.638049,3.160023,2.243799,5.073030
3,183,438,191,116,491,403,-6.164414,0.511117,0,272,...,4.168135,12.782579,0.513072,0.321295,11.334062,11.735511,1.911520,8.365676,4.877288,11.601819
4,449,156,310,188,279,465,8.000000,0.756416,1,90,...,7.908122,1.140498,14.165074,7.688796,5.079241,8.152186,1.680403,13.215111,5.823109,1.038015

In [23]:
number_of_rows, number_of_cols = train_data.shape
print("Number of rows: ", number_of_rows)
print("Number of columns: ", number_of_cols)
print("\nData type of each column: ")
print(train_data.dtypes)

Number of rows:  90000
Number of columns:  54

Data type of each column:
0           int64
1           int64
2           int64
3           int64
4           int64
5           int64
6         float64
7         float64
8           int64
9           int64
10          int64
11          int64
12          int64
13        float64
14        float64
15        float64
16        float64
17        float64
18        float64
19        float64
20        float64
21        float64
22        float64
23        float64
24        float64
25        float64
26        float64
27        float64
28        float64
29        float64
30        float64
31        float64
32        float64
33        float64
34        float64
35        float64
36        float64
37        float64
38        float64
39        float64
40        float64
41        float64
42        float64
43        float64
44        float64
45        float64
46        float64
47        float64
48        float64
49        float64
50        float64
51        float64
52        float64
target    float64
dtype: object

In [24]:
target_data = train_data[['target']].copy()
train_data = train_data.drop(['target'], axis=1)

In [25]:
x_train, x_true, y_train, y_true = train_test_split(train_data, target_data, test_size=0.25)

 Linear Regression

In [26]:
from sklearn.linear_model import LinearRegression

clf = LinearRegression(fit_intercept = True, copy_X = True, positive = True).fit(x_train, y_train)
predicted = clf.predict(x_true)

print(clf.score(x_true, y_true))

# The best possible score is 1.0 and it can be negative (because the model can be arbitrarily worse)

-0.00029914991904411714

In [27]:
MSE = mean_squared_error(y_true, predicted)
RMSE = math.sqrt(MSE)
print(f'Root Mean Square Error: {RMSE}')

Root Mean Square Error: 28.94550493909685

Decision Tree Regression
Decision tree regression is a non-parametric model that fits a tree structure to the data. It can capture complex nonlinear relationships between features and target variables, but may be prone to overfitting.

In [28]:
from sklearn.tree import DecisionTreeRegressor

regressor = DecisionTreeRegressor(max_depth=7, random_state=1).fit(x_train, y_train)
predicted = regressor.predict(x_true)

print(regressor.get_depth())
print(regressor.get_n_leaves())
print(regressor.score(x_true, y_true))

7
128
0.9964187918961486

In [29]:
print('Feature importances\n', list(zip(regressor.feature_importances_, np.arange(53))))

Feature importances
 [(0.0, 0), (0.0, 1), (0.0, 2), (0.0, 3), (0.0, 4), (0.0, 5), (0.9999898865934328, 6), (1.0113406567118696e-05, 7), (0.0, 8), (0.0, 9), (0.0, 10), (0.0, 11), (0.0, 12), (0.0, 13), (0.0, 14), (0.0, 15), (0.0, 16), (0.0, 17), (0.0, 18), (0.0, 19), (0.0, 20), (0.0, 21), (0.0, 22), (0.0, 23), (0.0, 24), (0.0, 25), (0.0, 26), (0.0, 27), (0.0, 28), (0.0, 29), (0.0, 30), (0.0, 31), (0.0, 32), (0.0, 33), (0.0, 34), (0.0, 35), (0.0, 36), (0.0, 37), (0.0, 38), (0.0, 39), (0.0, 40), (0.0, 41), (0.0, 42), (0.0, 43), (0.0, 44), (0.0, 45), (0.0, 46), (0.0, 47), (0.0, 48), (0.0, 49), (0.0, 50), (0.0, 51), (0.0, 52)]

RMSE

In [30]:
MSE = mean_squared_error(y_true, predicted)
RMSE = math.sqrt(MSE)
print(f'Root Mean Square Error: {RMSE}')

# RMSD is always non-negative, and a value of 0 
# (almost never achieved in practice) would indicate a 
# perfect fit to the data. In general,
# a lower RMSD is better than a higher one

Root Mean Square Error: 1.7319324901472768

In [31]:
prediction_for_test_data = regressor.predict(test_data)

In [32]:
prediction = pd.DataFrame(prediction_for_test_data, columns=['predictions']).to_csv('prediction.csv')